{{- if and .Values.openshift.enabled .Values.openshift.route.enabled -}}
{{- $fullName := include "strapi-sync-wizard.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- if .Values.openshift.route.router}}
    router: {{ .Values.openshift.route.router }}
    {{- else }}
    router: internal
    {{- end}}
    {{- include "strapi-sync-wizard.labels" . | nindent 4 }}
spec:
  {{- if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}