apiVersion: v1
entries:
  strapi-sync-wizard:
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2025-05-22T12:53:43.368037+02:00"
    description: A Helm chart for StrapiSyncWizard application
    digest: 6262185b64f3fb4e156969a37a1ca8ff067a08889163aade281013bff264303c
    home: https://github.com/ivseb/StrapiSyncWizard
    keywords:
    - strapi
    - sync
    - wizard
    - ktor
    - kotlin
    maintainers:
    - name: StrapiSyncWizard Team
    name: strapi-sync-wizard
    type: application
    urls:
    - https://ivseb.github.io/strapi-sync-wizard/charts/strapi-sync-wizard-0.2.0.tgz
    version: 0.2.0
generated: "2025-05-22T12:53:43.367395+02:00"
