apiVersion: v1
entries:
  strapi-sync-wizard:
  - apiVersion: v2
    appVersion: 0.0.7
    created: "2025-05-26T17:18:47.208349+02:00"
    description: A Helm chart for StrapiSyncWizard application
    digest: 261caf1c7fbef5df4ef7a824a8e095763015b295eab72339574f6bcfb3697c05
    home: https://github.com/ivseb/StrapiSyncWizard
    keywords:
    - strapi
    - sync
    - wizard
    - ktor
    - kotlin
    maintainers:
    - name: StrapiSyncWizard Team
    name: strapi-sync-wizard
    type: application
    urls:
    - https://ivseb.github.io/strapi-sync-wizard/charts/strapi-sync-wizard-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2025-05-26T17:18:47.208083+02:00"
    description: A Helm chart for StrapiSyncWizard application
    digest: 3561377bfe5e09be99236cdb1a75599052d251bbc868b8fa49fc487bd617f7fa
    home: https://github.com/ivseb/StrapiSyncWizard
    keywords:
    - strapi
    - sync
    - wizard
    - ktor
    - kotlin
    maintainers:
    - name: StrapiSyncWizard Team
    name: strapi-sync-wizard
    type: application
    urls:
    - https://ivseb.github.io/strapi-sync-wizard/charts/strapi-sync-wizard-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2025-05-26T17:18:47.207556+02:00"
    description: A Helm chart for StrapiSyncWizard application
    digest: 3c7f569d20c0b36281e95bb8c5b9615883182e9482ca2839bfcb5d754487993e
    home: https://github.com/ivseb/StrapiSyncWizard
    keywords:
    - strapi
    - sync
    - wizard
    - ktor
    - kotlin
    maintainers:
    - name: StrapiSyncWizard Team
    name: strapi-sync-wizard
    type: application
    urls:
    - https://ivseb.github.io/strapi-sync-wizard/charts/strapi-sync-wizard-0.2.0.tgz
    version: 0.2.0
generated: "2025-05-26T17:18:47.205624+02:00"
