apiVersion: v1
entries:
  strapi-sync-wizard:
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2025-05-22T12:57:05.730345+02:00"
    description: A Helm chart for StrapiSyncWizard application
    digest: 3c7f569d20c0b36281e95bb8c5b9615883182e9482ca2839bfcb5d754487993e
    home: https://github.com/ivseb/StrapiSyncWizard
    keywords:
    - strapi
    - sync
    - wizard
    - ktor
    - kotlin
    maintainers:
    - name: StrapiSyncWizard Team
    name: strapi-sync-wizard
    type: application
    urls:
    - https://ivseb.github.io/strapi-sync-wizard/charts/strapi-sync-wizard-0.2.0.tgz
    version: 0.2.0
generated: "2025-05-22T12:57:05.725295+02:00"
